# Generated by Django 6.0.7 on 2026-08-25 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('idAdministrador', models.AutoField(primary_key=True, serialize=False)),
                ('nombreAdministrador', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('idNotificacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('administrador', models.ForeignKey(db_column='idAdministrador', on_delete=django.db.models.deletion.CASCADE, to='administracion.administrador')),
            ],
        ),
    ]
