# Generated by Django 6.0.7 on 2026-08-25 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='administrador',
            table='Administrador',
        ),
        migrations.AlterModelTable(
            name='notificacion',
            table='Notificacion',
        ),
    ]
