# Generated by Django 6.0.7 on 2026-08-04 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('idMetodoPago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('idPago', models.AutoField(primary_key=True, serialize=False)),
                ('estadoPago', models.CharField(max_length=20)),
                ('codTransaccion', models.CharField(max_length=100)),
                ('fechaPago', models.DateField()),
                ('metodoPago', models.ForeignKey(db_column='idMetodoPago', on_delete=django.db.models.deletion.CASCADE, to='pagos.metodopago')),
                ('pedido', models.ForeignKey(db_column='idPedido', on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
            ],
        ),
    ]
