# Generated by Django 6.0.7 on 2026-08-25 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detallepedido',
            table='DetallePedido',
        ),
        migrations.AlterModelTable(
            name='pedido',
            table='Pedido',
        ),
    ]
