# Generated by Django 6.0.7 on 2026-08-25 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('idCarrito', models.AutoField(primary_key=True, serialize=False)),
                ('fechaCreacion', models.DateTimeField()),
                ('fechaExpiracion', models.DateTimeField(blank=True, null=True)),
                ('numeroPedido', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estadoPago', models.CharField(blank=True, max_length=20, null=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('precioUnitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subTotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cliente', models.ForeignKey(db_column='idCliente', on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='CarritoProducto',
            fields=[
                ('idCarritoProducto', models.AutoField(primary_key=True, serialize=False)),
                ('numeroPedido', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estadoPago', models.CharField(blank=True, max_length=20, null=True)),
                ('cantidad', models.IntegerField()),
                ('precioUnitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subTotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('carrito', models.ForeignKey(db_column='idCarrito', on_delete=django.db.models.deletion.CASCADE, to='carrito.carrito')),
                ('producto', models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
    ]
