# Generated by Django 6.0.7 on 2026-08-25 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carrito',
            table='Carrito',
        ),
        migrations.AlterModelTable(
            name='carritoproducto',
            table='CarritoProducto',
        ),
    ]
