# Generated by Django 6.0.6 on 2026-08-27 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_alter_carrito_table_alter_carritoproducto_table'),
        ('productos', '0004_remove_imagen_urlimagen_imagen_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoproducto',
            name='variante',
            field=models.ForeignKey(blank=True, db_column='idVariante', null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.productovariante'),
        ),
    ]
