# Generated by Django 6.0.7 on 2026-08-25 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precioCosto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precioVenta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IVA', models.DecimalField(decimal_places=2, default=21, max_digits=5)),
                ('descripcion', models.TextField()),
                ('porcentajeDescuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaInicioDescuento', models.DateTimeField(blank=True, null=True)),
                ('fechaFinDescuento', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(db_column='idCategoria', on_delete=django.db.models.deletion.CASCADE, to='productos.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('idImagen', models.AutoField(primary_key=True, serialize=False)),
                ('urlImagen', models.CharField(max_length=255)),
                ('producto', models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoVariante',
            fields=[
                ('idVariante', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=50)),
                ('talle', models.CharField(max_length=20)),
                ('stockProducto', models.IntegerField(default=0)),
                ('stockDeposito', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='productos.producto')),
            ],
        ),
    ]
