# Generated by Django 6.0.6 on 2026-08-25 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_categoria_table_alter_imagen_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='variante',
            field=models.ForeignKey(blank=True, db_column='idVariante', null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.productovariante'),
        ),
    ]
