# Generated by Django 6.0.6 on 2026-08-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_imagen_variante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='urlImagen',
        ),
        migrations.AddField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
