# Generated by Django 6.0.7 on 2026-08-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('DNI', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=150)),
                ('calle', models.CharField(max_length=150)),
                ('numCalle', models.CharField(max_length=10)),
                ('codPostal', models.CharField(max_length=10)),
                ('ciudad', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
            ],
        ),
    ]
